apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analyzer
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: ai-error-analyzer
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: ai-analyzer
      containers:
        - name: ai-analyzer
          env:
            - name: ENVIRONMENT
              value: prod
            - name: REDIS_HOST
              value: "team2-talkking-prod-redis.9iaedf.ng.0001.apn2.cache.amazonaws.com"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: ALERT_DATASOURCE_URL
              value: "jdbc:postgresql://team2-talkking-prod-alert-history-db.cne4w2cys26c.ap-northeast-2.rds.amazonaws.com:5432/errorops"
            - name: ALERT_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: talkking-db-secret
                  key: ALERT_DB_USERNAME
            - name: ALERT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: talkking-db-secret
                  key: ALERT_DB_PASSWORD
          envFrom:
            - secretRef:
                name: ai-error-analyzer-secret
