# dev ConfigMap Environment Variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: officetalk-env
  namespace: officetalk-dev
#스프링 부트가 실행될 때 application-dev.yml을 바라보도록 강제합니다.
SPRING_PROFILES_ACTIVE: dev

#스프링 부트 표준 DB 연결 환경 변수 규칙 적용
SPRING_DATASOURCE_URL: "jdbc:mysql://teamn-dev-db.xxxxxx.ap-northeast-2.rds.amazonaws.com:3306/officetalk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"

#스프링 부트 표준 레디스 / 카프카 환경 변수 명명 규칙 동기화
SPRING_DATA_REDIS_HOST: "teamn-dev-redis.xxxxxx.ng.0001.ap-northeast-2.cache.amazonaws.com"
SPRING_DATA_REDIS_PORT: "6379"

SPRING_KAFKA_BOOTSTRAP_SERVERS: "teamn-dev-kafka.xxxxxx.ap-northeast-2.amazonaws.com:9092"
