apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: talkking-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: talkking-app-secret
  namespace: talkking-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: talkking-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: team2-talkking/dev/database
