# dev ExternalSecret (AWS Secrets Manager)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: officetalk-db-secret
  namespace: officetalk-dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretstore # platform-addons에서 생성해둔 ClusterSecretStore 이름과 매핑
    kind: ClusterSecretStore
  target:
    name: officetalk-db-secret # 애플리케이션 Deployment가 참조할 최종 Secret 이름
    creationPolicy: Owner
  data:
  - secretKey: SPRING_DATASOURCE_PASSWORD
    remoteRef:
      key: dev/officetalk/db # AWS Secrets Manager에 저장된 Secret Name
      property: password     # JSON 키값
  - secretKey: SPRING_DATA_REDIS_PASSWORD
    remoteRef:
      key: dev/officetalk/redis
      property: password