#  team2-talkKing-config/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: talkking-dev

resources:
- ../../base
- global-config.yaml
- middleware-endpoints.yaml
- credential-secrets.yaml
- network-ingress.yaml
- services/auth/deployment-hpa.yaml
- services/chat/deployment-hpa.yaml
- services/frontend/deployment-hpa.yaml

  
images:
- name: talkking-chat
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team2-talkking/chat-service
  newTag: dbe2aaf18e28fda45ff540c8aeb9a12933287a65
- name: talkking-notification
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team2-talkking/notification-service
  newTag: dbe2aaf18e28fda45ff540c8aeb9a12933287a65
