apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: talkking-dev

resources:
  - ../../base
  - global-config.yaml
  - middleware-endpoints.yaml
  - credential-secrets.yaml
  - network-ingress.yaml
  - services/auth/deployment-hpa.yaml
  - services/chat/deployment-hpa.yaml
  - services/frontend/deployment-hpa.yaml