apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: officetalk-dev

resources:
  - ../../base
  - ./configmap-env.yaml
  - ./externalsecret-db.yaml
  - ./ingress.yaml
  - ./hpa-rules.yaml

patches:
  - path: ./patches.yaml