apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: talkking-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_RABBITMQ_PASSWORD
      remoteRef:
        key: dev/talkking/rabbitmq
        property: SPRING_RABBITMQ_PASSWORD
    - secretKey: rabbitmq-password
      remoteRef:
        key: dev/talkking/rabbitmq
        property: SPRING_RABBITMQ_PASSWORD
