apiVersion: v1
kind: ConfigMap
metadata:
  name: talkking-env
  namespace: talkking-dev
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://teamn-dev-db.xxxxxx.ap-northeast-2.rds.amazonaws.com:3306/talkking?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  SPRING_DATA_REDIS_HOST: "teamn-dev-redis.xxxxxx.ng.0001.ap-northeast-2.cache.amazonaws.com"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "teamn-dev-kafka.xxxxxx.ap-northeast-2.amazonaws.com:9092"