# team2-talkKing-config/overlays/dev/service/ai-analyzer/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analyzer
spec:
  replicas: 1 # Analyzer도 1개로 운영
  template:
    spec:
      containers:
        - name: ai-analyzer
          env:
            - name: ENVIRONMENT
              value: "dev"
            # Secret이나 ConfigMap에서 값 가져오기 (예시)
            # - name: SLACK_WEBHOOK_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: credential-secrets
            #       key: slack-webhook