apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: "762131618818.dkr.ecr.ap-northeast-2.amazonaws.com/talkking-frontend:dev-1.0"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-service-hpa
  namespace: talkking-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80