# prod ExternalSecret (AWS Secrets Manager)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: officetalk-db-secret
  namespace: officetalk-prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: officetalk-db-secret
    creationPolicy: Owner
  data:
  - secretKey: SPRING_DATASOURCE_PASSWORD
    remoteRef:
      key: prod/officetalk/db
      property: password
  - secretKey: SPRING_DATA_REDIS_PASSWORD
    remoteRef:
      key: prod/officetalk/redis
      property: password