apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: talkking-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talkking-app-secret
  namespace: talkking-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: talkking-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: team2-talkking/prod/database
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: team2-talkking/prod/database
        property: password
    - secretKey: ALERT_DB_USERNAME
      remoteRef:
        key: team2-talkking/prod/alert-history-db
        property: username
    - secretKey: ALERT_DB_PASSWORD
      remoteRef:
        key: team2-talkking/prod/alert-history-db
        property: password
