# prod HPA / AutoScaling Rules
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-service-keda
  namespace: officetalk-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 2 # prod 환경 최소 가용성 확보를 위해 2개로 시작
  maxReplicas: 10
  cooldownPeriod: 300
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: teamn-prod-msk-broker1.xxxxxx.ap-northeast-2.amazonaws.com:9092
      consumerGroup: notification-group
      topic: chat.message.created
      lagThreshold: "100" # 소비 지연 메시지가 100개 이상 쌓이면 오토스케일링 발동