apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: talkking-prod

resources:
  - ../../base
  - global-config.yaml
  - middleware-endpoints.yaml
  - credential-secrets.yaml
  - network-ingress.yaml
  - services/auth/deployment-policy.yaml
  - services/chat/deployment-policy.yaml
  - services/frontend/deployment-policy.yaml
  - services/notification/deployment-keda.yaml