# prod Patches (Image tags, replicas, resource overrides)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service # base에 선언된 디플로이먼트 이름과 맵핑 (kustomization.yaml이 네임스페이스를 일괄 자동 패치합니다)
spec:
  template:
    spec:
      # 운영 환경 Pod 간 Multi-AZ 균등 분산을 위한 토폴로지 제약 추가
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfied: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: auth
      containers:
      - name: auth-service
        image: xxxxxxxxxxxx.dkr.ecr.ap-northeast-2.amazonaws.com/talkking-auth:prod-stable # 💡 프로젝트명 talkking 반영
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  template:
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfied: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chat
      containers:
      - name: chat-service
        image: xxxxxxxxxxxx.dkr.ecr.ap-northeast-2.amazonaws.com/talkking-chat:prod-stable # 💡 프로젝트명 talkking 반영