apiVersion: apps/v1
kind: Deployment
metadata:
  name: talkking-notification
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfied: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: talkking-notification
      containers:
        - name: talkking-notification
