apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-rabbitmq-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: rabbitmq

    # 실제 최신 차트 버전으로 지정
    targetRevision: 16.0.6

    helm:
      values: |
        fullnameOverride: rabbitmq-service

        architecture: standalone

        auth:
          username: talkking
          existingPasswordSecret: rabbitmq-secret
          existingSecretPasswordKey: rabbitmq-password

        image:
          registry: docker.io
          repository: bitnami/rabbitmq
          tag: 4.3.0

        persistence:
          enabled: false

        service:
          type: ClusterIP

        metrics:
          enabled: true

          serviceMonitor:
            enabled: true
            namespace: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: talkking-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true