apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-rabbitmq-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # 🛡️ [보안 통과]: 방화벽에 막히는 깃허브 주소 대신, 안전한 공식 OCI 주소로 복구하여 보안을 통과합니다.
    repoURL: registry-1.docker.io/bitnamicharts
    chart: rabbitmq
    targetRevision: "*"
    helm:
      values: |
        fullnameOverride: rabbitmq-service
        architecture: standalone
        replicaCount: 1

        # 🎯 [레거시 저장소 강제 지정]: 도커 허브의 레거시 보관소 주소로 우회합니다.
        image:
          registry: docker.io
          repository: bitnami/rabbitmq
          tag: 4.0.9-0-r01

        auth:
          username: talkking
          existingPasswordSecret: rabbitmq-secret
          existingSecretPasswordKey: rabbitmq-password

        persistence:
          enabled: false

        service:
          type: ClusterIP

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: talkking-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true