# ArgoCD Root App - DEV
# team2-talkKing-config/argocd/root-application-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-root-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # 리소스 삭제 시 깔끔하게 정리해주는 옵션 (추가)
spec:
  project: default
  source:
    repoURL: 'https://github.com/CLD-05/team2-talkKing-config' # 👈 우리 팀의 Config 깃허브 주소
    targetRevision: HEAD 
    path: overlays/dev 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: talkking-dev # EKS 안에서 dev 환경이 배포될 네임스페이스
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true # ★ dev 네임스페이스가 없으면 자동으로 만들어주는 아주 좋은 옵션 (추가)