apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  template:
    spec:
      containers:
        - name: chat-service
          envFrom:
            - configMapRef:
                name: talkking-env
            - secretRef:
                name: talkking-db-secret
            - secretRef:
                name: rabbitmq-secret
