# team2-talkKing-config/base/chat-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-service
        image: talkking-chat:latest
        ports:
        - containerPort: 8080
          name: websocket
        envFrom:
        - configMapRef:
            name: talkking-env
        - secretRef:
            name: talkking-db-secret
        resources:
          requests:
            cpu: "250m"
          # 💡 메모리가 부족하면 기동 속도가 느려질 수 있으므로 Requests 버퍼 확보
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        # ⏱️ [최종 교정]: 스프링 부트가 65초간 안심하고 부팅할 수 있도록 80초의 유예 시간을 줍니다.
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 80  # 👈 40에서 80으로 늘려 쿠버네티스의 성급한 억울한 킬을 원천 차단
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 80  # 👈 동일하게 80으로 튜닝
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: websocket
  selector:
    app: chat
  type: ClusterIP
---
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chat-service-monitor
  namespace: talkking-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: chat
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s