apiVersion: v1
kind: ServiceAccount
metadata:
  name: fis-experiment
  namespace: talkking-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fis-pod-modifier
  namespace: talkking-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "delete", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fis-pod-modifier-binding
  namespace: talkking-dev
subjects:
  - kind: ServiceAccount
    name: fis-experiment
    namespace: talkking-dev
roleRef:
  kind: Role
  name: fis-pod-modifier
  apiGroup: rbac.authorization.k8s.io
